export default {
  index: { title: '简介', display: 'hidden' },
  'preface': { title: '前言 — 为什么要读一个 Agent 项目的源码', display: 'hidden' },
  'overview': 'OpenClaw 全景：从 Clawdbot 到 350K Stars',
  'project-structure': '项目工程结构：Monorepo、模块划分与构建体系',
  'quickstart': '快速上手：本地部署你的第一个 Agent',
  'gateway': 'Gateway 架构：单进程守护与 WebSocket 协议设计',
  'request-lifecycle': '请求生命周期：从消息到达到响应返回的完整链路',
  'session': 'Session 管理：单写者模型与 Lane-aware 命令队列',
  'streaming': '流式响应：分块输出、段落感知与 NO_REPLY 机制',
  'system-prompt': 'System Prompt 组装：动态拼装的工程艺术',
  'tool-system': '工具系统：注册、发现、策略与执行',
  'bash-tools': 'Bash 工具：进程管理、PTY 与沙箱执行',
  'model-provider': 'Model Provider 抽象：多模型统一接入与故障转移',
  'context-window': 'Context Window 管理：Compaction、Pruning 与预算控制',
  'bootstrap-files': 'Bootstrap Files — SOUL.md 与文件驱动的 Agent 人格',
  'skills': 'Skills 系统：元数据索引与按需加载',
  'memory': 'Memory 系统：四层记忆架构与混合检索',
  'heartbeat-cron': 'Heartbeat 与 Cron：Agent 的主动行为机制',
  'channel-bridge': 'Channel Bridge：25+ 渠道的统一消息抽象',
  'multi-agent': '多 Agent 路由：Bindings、Workspace 隔离与会话分发',
  'sub-agent': 'Sub-Agent 系统：异步编排与结构化通信',
  'canvas-a2ui': 'Canvas 与 A2UI：Agent 驱动的可视化界面',
  'voice-tts': 'Voice 与 TTS：语音交互全链路',
  'browser': 'Browser 自动化：CDP、Playwright 与网页操作',
  'security': '七层安全模型：从认证到沙箱的纵深防御',
  'security-cases': '实战安全分析：真实漏洞、恶意 Skill 与 Prompt 注入',
  'deployment': '生产部署：从单机到 Kubernetes 的架构演进',
  'plugin-extension': 'Plugin 与 Extension 开发：扩展 Gateway 能力',
  'build-skill': '实战：从零开发一个 OpenClaw Skill',
  'build-channel': '实战：开发一个 Channel Extension',
  'mini-design': 'Mini OpenClaw 架构设计',
  'mini-gateway': '实现 Gateway 与 Session 核心',
  'mini-agent': '实现 Agent Runtime 与工具执行',
  'mini-memory-skills': '实现 Memory 与 Skills 加载',
  'mini-channel': '接入消息渠道与端到端联调',
  'design-patterns': 'OpenClaw 的 10 个核心设计模式',
};
