export default {
  index: { title: '简介', display: 'hidden' },
  'preface': '前言',
  'problem-domain': 'Agent Memory 问题域',
  'claude-mem-intro': '认识 claude-mem — 能力全景与快速上手',
  'context-engineering': 'Context Engineering 基础',
  'system-overview': '系统架构总览',
  'hook-lifecycle': 'Hook 驱动的生命周期',
  'worker-service': 'Worker Service — 异步处理引擎',
  'storage': '存储层设计',
  'progressive-disclosure': 'Progressive Disclosure — 渐进式信息披露',
  'mcp-search': 'MCP 搜索架构',
  'observation-system': 'Observation 系统',
  'knowledge-agent': 'Knowledge Agent — 知识库构建',
  'dev-setup': '开发环境搭建',
  'mini-mem': '实现简版 Memory Plugin（mini-mem）',
  'extensions': '进阶功能扩展',
  'industry-survey': '业界 Agent Memory 方案调研',
  'platform-upgrade': '从 Plugin 到平台的架构升级',
  'enterprise-features': '企业级特性设计',
  'frontier': '前沿探索',
};
