export default {
  index: { title: '简介', display: 'hidden' },
  'preface': '前言',
  'problem-domain': '第 1 章：Agent Memory 问题域',
  'claude-mem-intro': '第 2 章：认识 claude-mem — 能力全景与快速上手',
  'context-engineering': '第 3 章：Context Engineering 基础',
  'system-overview': '第 4 章：系统架构总览',
  'hook-lifecycle': '第 5 章：Hook 驱动的生命周期',
  'worker-service': '第 6 章：Worker Service — 异步处理引擎',
  'storage': '第 7 章：存储层设计',
  'progressive-disclosure': '第 8 章：Progressive Disclosure — 渐进式信息披露',
  'mcp-search': '第 9 章：MCP 搜索架构',
  'observation-system': '第 10 章：Observation 系统',
  'knowledge-agent': '第 11 章：Knowledge Agent — 知识库构建',
  'dev-setup': '第 12 章：开发环境搭建',
  'mini-mem': '第 13 章：实现简版 Memory Plugin（mini-mem）',
  'extensions': '第 14 章：进阶功能扩展',
  'industry-survey': '第 15 章：业界 Agent Memory 方案调研',
  'platform-upgrade': '第 16 章：从 Plugin 到平台的架构升级',
  'enterprise-features': '第 17 章：企业级特性设计',
  'frontier': '第 18 章：前沿探索',
};
