export default {
  index: '简介',
  'ch00-python-quickstart': '第 0 章：Python 环境与快速入门',
  'ch01-overview': '第 1 章 全景图：LLM 技术栈的分层',
  'ch02-transformer': '第 2 章 Transformer 架构：工程师视角',
  'ch03-gpu-basics': '第 3 章 GPU 与计算基础',
  'ch04-inference-basics': '第 4 章 模型推理：从权重文件到 API 响应',
  'ch05-vllm': '第 5 章 vLLM：工业级推理引擎深度剖析',
  'ch06-engines-comparison': '第 6 章 推理引擎对比与选型',
  'ch07-quantization': '第 7 章 量化：用更少的显存跑更大的模型',
  'ch08-inference-optimization': '第 8 章 推理加速技术',
  'ch09-finetuning': '第 9 章 微调：让通用模型变成领域专家',
  'ch10-alignment': '第 10 章 RLHF 与对齐',
  'ch11-distributed-training': '第 11 章 分布式训练基础',
  'ch12-production-deploy': '第 12 章 LLM 服务的生产化部署',
  'ch13-observability-cost': '第 13 章 可观测性与成本优化',
  'ch14-rag-infra': '第 14 章 RAG 系统的基础设施',
  'ch15-multimodal': '第 15 章 多模态模型的基础设施',
  'ch16-career-path': '第 16 章 从 Agent 开发者到 Infra 工程师：职业路径',
};
