export default {
  index: { title: '简介', display: 'hidden' },
  'python-quickstart': 'Python 环境与快速入门',
  'overview': '全景图：LLM 技术栈的分层',
  'transformer': 'Transformer 架构：工程师视角',
  'gpu-basics': 'GPU 与计算基础',
  'inference-basics': '模型推理：从权重文件到 API 响应',
  'vllm': 'vLLM：工业级推理引擎深度剖析',
  'engines-comparison': '推理引擎对比与选型',
  'quantization': '量化：用更少的显存跑更大的模型',
  'inference-optimization': '推理加速技术',
  'finetuning': '微调：让通用模型变成领域专家',
  'alignment': 'RLHF 与对齐',
  'distributed-training': '分布式训练基础',
  'production-deploy': 'LLM 服务的生产化部署',
  'observability-cost': '可观测性与成本优化',
  'rag-infra': 'RAG 系统的基础设施',
  'multimodal': '多模态模型的基础设施',
  'career-path': '从 Agent 开发者到 Infra 工程师：职业路径',
};
