export default {
  index: { title: '简介', display: 'hidden' },
  'preface': '前言',
  'chatbot-to-agent': '从 Chatbot 到 Agent:一条尚未走完的路',
  'quickstart': '10 分钟跑通你的第一个 Hermes',
  'memory-system': '记忆系统:从 Chat History 到分层知识',
  'skill-mechanism': '技能系统的机制:生命周期与质量闸门',
  'skill-showcase': 'Hermes 明星 Skill 解剖',
  'learning-loop': '学习闭环:Agent 如何"知道自己进步了"',
  'execution-engine': '执行引擎与多模型路由',
  'integration': '让 Agent 接入世界:MCP、消息网关、Cron',
  'deployment': '部署拓扑与多设备共享',
  'observability': '可观测性:让自学习可回放',
  'security': '安全、沙箱与失败模式档案',
  'evaluation': '评估:你的 Agent 真的在变好吗',
  'paradigm-comparison': '与其他 Agent 范式的深度对比',
  'case-studies': '三个端到端案例精讲',
  'mini-hermes-part1': '用 TypeScript 从零构造 mini-hermes(上):骨架与记忆',
  'mini-hermes-part2': 'mini-hermes(下):让它自己写 Skill',
};
