export default {
  index: { title: '简介', display: 'hidden' },
  'chapter-01': '从浏览器到终端',
  'chapter-02': '命令设计的艺术',
  'chapter-03': '交互式体验',
  'chapter-04': '输出的艺术',
  'chapter-05': '配置管理',
  'chapter-06': '登录鉴权',
  'chapter-07': '网络请求',
  'chapter-08': '接入大模型 -- 基础能力',
  'chapter-09': 'AI Agent 模式 -- 进阶能力',
  'chapter-10': '错误处理与调试',
  'chapter-11': '测试与发布',
  'chapter-12': '插件系统设计',
  'chapter-13': 'Ink + React — 组件化终端界面',
  'chapter-14': '面向未来 — CLI 作为 AI 基础设施',
};
